### ISSUE TITLE
help needed: bundling viz.js with webpack 5

### ISSUE THREAD

**Issue by christianvoigt** [aduh95/viz.js#17]
Hi, sorry to bother you again (I promise it will be my last issue for the coming months), but I just cannot get bundling viz.js with webpack 5 to work (and I already have spent way too much time on this).

I am using ts-loader, file-loader, worker-loader and your [example](https://github.com/aduh95/viz.js#using-a-bundler) from the README. If I try to to use `import initWASM from "@aduh95/viz.js/worker";` webpack uses the `.mjs` file and does not find a lot of modules (e.g. "module", "process", "util", "url" and so on). Webpack 5 is supposed to work with package.json exports, but somehow it does not pick the "browser" export. Or is this caused by Typescript?

So I switched to `import initWASM from "../node_modules/@aduh95/viz.js/dist/render.browser.js";` like you proposed in the Readme. I had to change the worker file to `.js` for that as Typescript would not allow me to use this import statement. Now webpack complains about import and export statements in `render.browser.js`:

```
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module'
```

I tried to use `"type":"module"` in my own package.json, but that does not help. Maybe I am totally confused about the current state of node/js module systems at the moment, but I suspect other users are in a similar state. I think it would be great if you could add a small example with webpack 5 in the `/test` folder.

**Comment by aduh95** [comment]
Hum, OK so I tried to setup a Webpack 5 prooject, and indeed it needs to tweaking to make it work. There are two issues:

- Webpack loads the `import` version instead of the `browser` one as you pointed out.
- Webpack thinks `render.browser.js` is not an ES module for some reason.

I was able to have Webpack compile my stuff by applying that diff to `./node_modules/@aduh95/viz.js/package.json`:

```diff
18,19c18,19
<       "import": "./dist/render.node.mjs",
<       "browser": "./dist/render.browser.js"
---
>       "node": "./dist/render.node.mjs",
>       "import": "./dist/render.browser.js"
22c22
<   "type": "commonjs",
---
>   "type": "module",
```

It's clearly a hack, I wish I knew Webpack better to understand why it's not picking this up correctly – surely there's a settings to toggle or something to have it work properly. If you just need a quick fix, you can use the `patch-package` package to unblock you.

**Comment by christianvoigt** [comment]
Thanks for your help, at least now I no longer have the feeling that I was missing something obvious. I am thinking about my options now:

- just take your patch and let it go (but I have some Argdown users that were struggling with bundling my library, so that is not ideal)
- switch to a different bundler (do you have any recommendation? Are you using one at all?)
- post this as an issue at the webpack repository (do you think that makes sense? At least  we might get a hint what that magic toggle might be)

**Comment by aduh95** [comment]
So I dug this a bit deeper and tried to make a Rollup setup, and I guess `"exports"` conditions just don't work as I thought it would: like Webpack, `@rollup/plugin-node` always prefers `"import"` even if there's a `"browser"` entry.

I need to find out what would be the correct configuration, any help is welcome.

> * (do you have any recommendation? Are you using one at all?)

On https://github.com/aduh95/viz.js-playground, I'm using Webpack v4 (v5 wasn't available when this started), so it's not using package exports. But viz.js should work on any bundler, ideally with a minimum amount of boilerplate and config – and with no bundler at all.

> * post this as an issue at the webpack repository (do you think that makes sense? At least  we might get a hint what that magic toggle might be)

It would be surprising we are the first to stumble upon this, but if there are no open ticket on the subject, yeah it would make sense to open one, so they can improve the documentation.

**Comment by christianvoigt** [comment]
Are you already using babel-loader in your webpack configuration? I just found [this](https://github.com/webpack-contrib/worker-loader#integrating-with-es6-features) in the worker-loader Readme. There is also a [section](https://github.com/webpack-contrib/worker-loader#integrating-with-typescript) about how to get this working with Typescript.

I will also try out Parcel 2 (beta). [This issue](https://github.com/parcel-bundler/parcel/issues/3959) describes how to use it with web workers.

**Comment by christianvoigt** [comment]
This might also be relevant: [web-worker](https://github.com/developit/web-worker) npm package.

Found in the above thread in this paragraph:

> I don't know any remotely reasonable way to publish a CJS build with worker instantiation code that works in node (including Windows) and browsers, and can also be handled by most bundlers. I believe web-worker is supposed to help with this, but I never got it to work.

**Comment by christianvoigt** [comment]
I tried Parcel 2 but ended up with a `no transformer found` error for the wasm file (which is supposed to work, I do not know why parcel does not recognize the file format). I have not found any information for this error, so maybe I should also create an issue for that, but for now I want to enjoy my weekend.

I also followed the instructions from the worker-loader Readme, but that did not help with the webpack 5 problems.

**Comment by aduh95** [comment]
@christianvoigt Can you please confirm that the change in https://github.com/aduh95/viz.js/pull/19 solves the issue and the README is intelligible? :)

**Comment by christianvoigt** [comment]
In my webpack test project webpack still loads `render.node.mjs` instead of `render.browser.mjs`.

Do I have to change anything in my code? I downloaded the build from the pull request and put it in my node_modules folder. I read the changes in the Readme, but the example code for webpack is the same as before, right? "documented in the comments in this PR" -- do you mean the new comments in the Readme file?

Could you send me your webpack config? Here is my current one:

```javascript
import path from "path";
import HtmlWebpackPlugin from "html-webpack-plugin";
import clean from "clean-webpack-plugin";
import webpack from "webpack";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
export default {
  mode: "development",
  target: "web",
  entry: "./src/index.ts",
  devtool: "inline-source-map",
  module: {
    rules: [
      {
        test: /^worker-loader!/,
        use: [
          {
            loader: "worker-loader",
          },
          {
            loader: "babel-loader",
            options: {
              presets: ["@babel/preset-env"],
            },
          },
        ],
      },
      {
        test: /\.tsx?$/,
        use: "ts-loader",
        exclude: /node_modules/,
      },
      {
        test: /^file-loader!/,
        use: "file-loader",
        exclude: /node_modules/,
      },
    ],
  },
  plugins: [
    new clean.CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      hash: true,
      template: "./src/index.html",
    }),
    new webpack.ProvidePlugin({
      Buffer: ["buffer", "Buffer"],
      process: "process",
    }),
  ],
  resolve: {
    extensions: [".tsx", ".ts", ".js"],
  },
  output: {
    filename: "bundle.js",
    path: path.resolve(__dirname, "dist"),
  },
  devServer: {
    contentBase: "./dist",
  },
  experiments: { asyncWebAssembly: true },
};

```

**Comment by aduh95** [comment]
I used this one for the small repro:

```js
const path = require("path");
module.exports = {
  entry: "./src/index.js",
  output: {
    path: path.join(__dirname, "dist"),
    filename: "bundle.js",
  },
};
```

And here's the `package.json`:

```json
{
  "dependencies": {
    "@aduh95/viz.js": "^3.3.2"
  },
  "devDependencies": {
    "file-loader": "^6.2.0",
    "webpack": "^5.23.0",
    "webpack-cli": "^4.5.0",
    "worker-loader": "^3.0.8"
  },
  "scripts": {
    "build": "webpack --stats-children"
  }
}
```

> Do I have to change anything in my code?

No, I didn't change the Webpack example, it's still the same code indeed.

> In my webpack test project webpack still loads `render.node.mjs` instead of `render.browser.mjs`.

That really should not happen… I think what's happening is the package manager you are using (`npm`, `yarn`?) reverts the changes to use the version published on `npm` – or maybe you didn't copy the `package.json` file, but only the `dist` folder?

**Comment by christianvoigt** [comment]
You are right, I accidentally deleted the `viz.js` folder and put the new files  directly into `node_modules/@aduh95`. 

With your config, everything is fine now. Switching to my configuration (adding Typescript support), `render.browser.mjs` is loaded correctly, but I still get the following error:

```
 ERROR in ./node_modules/@aduh95/viz.js/dist/render.wasm (./node_modules/file-loader/dist/cjs.js!./node_modules/@aduh95/viz.js/dist/render.wasm)
  Module parse failed: magic header not detected
  File was processed with these loaders:
   * ./node_modules/file-loader/dist/cjs.js
  You may need an additional loader to handle the result of these loaders.
  Error: magic header not detected
```

**Comment by christianvoigt** [comment]
Got it, I forgot to remove `experiments: { asyncWebAssembly: true },` which was causing this error.

Thanks a lot for your work!
