### ISSUE TITLE
TS 3.7 compatible

### ISSUE THREAD

**Issue by igbopie** [aduh95/viz.js#4]
Hi,

We can't upgrade our project to typescript 3.8 yet, and we can't use (as it is) this dependency. The change would be this:

```
import type { Worker as NodeJSWorker } from "worker_threads";
import type { RenderOptions, GraphvizJSONOutput } from "./types";
```
to 
```
import { Worker as NodeJSWorker } from "worker_threads";
import { RenderOptions, GraphvizJSONOutput } from "./types";
```

This will make it compatible with older versions. Let me know!

**Comment by igbopie** [comment]
So far the workaround for us is to do this:

tsconfig.json
```
"@aduh95/viz.js": ["types/modules/viz.js.d.ts"],
```

then copy paste contents of d.ts file and fix it.

**Comment by aduh95** [comment]
Hi! I'm not sure this would be the right thing to do... 

I think it's fair to target the latest TS version. As far as I know, there are no breaking changes from 3.7 to 3.8, so it should not be a big deal for most projects to just update their TS version.

For users that don't want to or cannot update their TS version, they could either create a `viz.js.d.ts` as you mentioned, or use something like [patch-package](https://github.com/ds300/patch-package) or [Yarn plugin-patch](https://yarnpkg.com/api/modules/plugin_patch.html) to fix the syntax. The patch file would be:

```diff
diff --git a/node_modules/@aduh95/viz.js/dist/index.d.ts b/node_modules/@aduh95/viz.js/dist/index.d.ts
index e46241f..e3116e2 100644
--- a/node_modules/@aduh95/viz.js/dist/index.d.ts
+++ b/node_modules/@aduh95/viz.js/dist/index.d.ts
@@ -1,3 +1,3 @@
 /// <reference types="node" />
-import type { Worker as NodeJSWorker } from "worker_threads";
-import type { RenderOptions, GraphvizJSONOutput } from "./types";
+import { Worker as NodeJSWorker } from "worker_threads";
+import { RenderOptions, GraphvizJSONOutput } from "./types";

```

If you think this is not acceptable, I'm open to being persuade by a strong argument.

**Comment by igbopie** [comment]
I understand. No problem.

By the way, 3.8 breaks ember hehe (https://github.com/typed-ember/ember-cli-typescript/issues/1103)
