### ISSUE TITLE
Cannot import render.browser.js

### ISSUE THREAD

**Issue by dlredden** [aduh95/viz.js#7]
`import wasmURL from '@aduh95/viz.js/dist/render.browser';`
results in the following error. 

ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Unexpected token (10:17)
File: node_modules/@aduh95/viz.js/dist/render.browser.js:10:17

I've tried `const wasmURL = require...` and `import(...).then` and all end in the same result. This leads me to believe that it's an issue in the `render.browser.js` file but that seems unlikely.

I'm kinda out of ideas and looking for suggestions on what the underlying issue could be.

I'm using Gatsby which uses Webpack. I also had the same issue with NextJS which uses Webpack as well.

**Comment by aduh95** [comment]
Are you using Webpack 4? Webpack 4 doesn't support ESM out of the box, so it gives up as soon as it meets the `import` keyword. To workaround this issue, you can either use Babel to convert the module to CJS syntax, either use Webpack v5 (currently in beta, but it seems pretty stable).

**Comment by aduh95** [comment]
Actually, after doing a little more research on this, it turns out the `import.meta.url` is added by emscripten but never used afterwards. I tried to remove it on my local build, and it then works fine with Webpack v4! You can disregard my previous comment.
